# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [2]:
import numpy as np

#### Create an array of 10 zeros 

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [5]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [6]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [7]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [11]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [13]:
np.random.normal(0,1)

-0.5055412602999707

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [14]:
np.random.normal(size=25)

array([-0.30529316, -1.13302823,  0.46436019, -1.98600995,  0.3326285 ,
        1.39909319, -0.43500154, -1.52686607, -0.98908905, -1.28734953,
        0.37064583, -0.0559226 ,  0.97701214, -0.68406372,  0.8444696 ,
       -1.92618705, -1.21355272, -0.17325519, -0.67884677,  0.21300994,
        0.8018037 , -1.66159011, -0.01290582, -0.83719968,  1.21500032])

#### Create the following matrix:

In [20]:
np.random.random((10,10))

array([[0.89796084, 0.26557499, 0.45647932, 0.32956749, 0.03150264,
        0.44638207, 0.54322744, 0.70623021, 0.47784201, 0.82406396],
       [0.61635156, 0.83231873, 0.10861304, 0.60654199, 0.88578466,
        0.45265315, 0.68000167, 0.23606263, 0.45010197, 0.12753795],
       [0.87074181, 0.74918027, 0.36814939, 0.58595762, 0.93260482,
        0.49645671, 0.73645202, 0.80303241, 0.7444725 , 0.08294577],
       [0.32256462, 0.99093109, 0.27149653, 0.27681475, 0.35742813,
        0.48933812, 0.93176232, 0.09558076, 0.12483505, 0.68470954],
       [0.5013664 , 0.84898601, 0.80060219, 0.40150818, 0.61578534,
        0.83603821, 0.22661073, 0.71268196, 0.30959064, 0.15816469],
       [0.04203468, 0.80905744, 0.38301394, 0.24222207, 0.7080713 ,
        0.62189292, 0.93226045, 0.09037106, 0.14054286, 0.60584403],
       [0.48905753, 0.03094211, 0.88912936, 0.21020231, 0.63308881,
        0.45852114, 0.64981523, 0.20230374, 0.09888709, 0.73652995],
       [0.97620826, 0.82158823, 0.7165391

In [19]:
np.random.random((1,20))

array([[0.12537444, 0.34688709, 0.5800142 , 0.74749386, 0.10590268,
        0.12169937, 0.18760217, 0.26911667, 0.19549758, 0.17193916,
        0.49373809, 0.830669  , 0.61086218, 0.00529394, 0.26728261,
        0.50596974, 0.01210547, 0.29005649, 0.01501271, 0.57214499]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [21]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [39]:
matrix = np.arange(1,26).reshape(5,5)
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [29]:
matrix[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [34]:
matrix[3:4,4:5][0,0]

20

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [41]:
matrix[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [42]:
matrix[4]

array([21, 22, 23, 24, 25])

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [45]:
matrix[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [26]:
matrix.sum()

325

#### Get the standard deviation of the values in mat

In [27]:
matrix.std()

7.211102550927978

#### Get the sum of all the columns in mat

In [28]:
matrix.sum(axis=0)

array([55, 60, 65, 70, 75])

In [46]:
matrix.sum(axis=1)

array([ 15,  40,  65,  90, 115])

# Great Job!